#!/bin/bash

oklb_id=$(xinput | grep "OLKB Preonic  " | awk '{print $4}' | cut -c 4-)

xkbcomp -i $oklb_id /home/johannes/Dropbox/technical_stuff_general/dotfiles/preonic_keys.xkb $DISPLAY

xset r rate 210 30

# echo $oklb_id
